services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: db_name
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - "5432:5432"
  backend:
    image: symoney/cee-backend:latest
    env_file:
      - .env.dev
    container_name: backend
    ports:
      - "8000:8000"
    restart: always

volumes:
  postgres_data:

  